import json

def genetic_codes():
    """
    The genetic codes. This has been imported from codes/ncbi.json, and is provided to hopefully make things
    slightly faster than reading that file
    :return: a dictionary of translation tables, their initiators, and their codons
    """
    return json.loads('{"1": {"initiators": ["TTG", "CTG", "ATG"], "codons": {"TTT": "Phe", "TCT": "Ser", '
                      '"TAT": "Tyr", "TGT": "Cys", "TTC": "Phe", "TCC": "Ser", "TAC": "Tyr", "TGC": "Cys", '
                      '"TTA": "Leu", "TCA": "Ser", "TAA": "Ter", "TGA": "Ter", "TTG": "Leu", "TCG": "Ser", '
                      '"TAG": "Ter", "TGG": "Trp", "CTT": "Leu", "CCT": "Pro", "CAT": "His", "CGT": "Arg", '
                      '"CTC": "Leu", "CCC": "Pro", "CAC": "His", "CGC": "Arg", "CTA": "Leu", "CCA": "Pro", '
                      '"CAA": "Gln", "CGA": "Arg", "CTG": "Leu", "CCG": "Pro", "CAG": "Gln", "CGG": "Arg", '
                      '"ATT": "Ile", "ACT": "Thr", "AAT": "Asn", "AGT": "Ser", "ATC": "Ile", "ACC": "Thr", '
                      '"AAC": "Asn", "AGC": "Ser", "ATA": "Ile", "ACA": "Thr", "AAA": "Lys", "AGA": "Arg", '
                      '"ATG": "Met", "ACG": "Thr", "AAG": "Lys", "AGG": "Arg", "GTT": "Val", "GCT": "Ala", '
                      '"GAT": "Asp", "GGT": "Gly", "GTC": "Val", "GCC": "Ala", "GAC": "Asp", "GGC": "Gly", '
                      '"GTA": "Val", "GCA": "Ala", "GAA": "Glu", "GGA": "Gly", "GTG": "Val", "GCG": "Ala", '
                      '"GAG": "Glu", "GGG": "Gly"}}, "2": {"initiators": ["GTG", "ATC", "ATA", "ATT", "ATG"], '
                      '"codons": {"TTT": "Phe", "TCT": "Ser", "TAT": "Tyr", "TGT": "Cys", "TTC": "Phe", "TCC": "Ser", '
                      '"TAC": "Tyr", "TGC": "Cys", "TTA": "Leu", "TCA": "Ser", "TAA": "Ter", "TGA": "Trp", '
                      '"TTG": "Leu", "TCG": "Ser", "TAG": "Ter", "TGG": "Trp", "CTT": "Leu", "CCT": "Pro", '
                      '"CAT": "His", "CGT": "Arg", "CTC": "Leu", "CCC": "Pro", "CAC": "His", "CGC": "Arg", '
                      '"CTA": "Leu", "CCA": "Pro", "CAA": "Gln", "CGA": "Arg", "CTG": "Leu", "CCG": "Pro", '
                      '"CAG": "Gln", "CGG": "Arg", "ATT": "Ile", "ACT": "Thr", "AAT": "Asn", "AGT": "Ser", '
                      '"ATC": "Ile", "ACC": "Thr", "AAC": "Asn", "AGC": "Ser", "ATA": "Met", "ACA": "Thr", '
                      '"AAA": "Lys", "AGA": "Ter", "ATG": "Met", "ACG": "Thr", "AAG": "Lys", "AGG": "Ter", '
                      '"GTT": "Val", "GCT": "Ala", "GAT": "Asp", "GGT": "Gly", "GTC": "Val", "GCC": "Ala", '
                      '"GAC": "Asp", "GGC": "Gly", "GTA": "Val", "GCA": "Ala", "GAA": "Glu", "GGA": "Gly", '
                      '"GTG": "Val", "GCG": "Ala", "GAG": "Glu", "GGG": "Gly"}}, "3": {"initiators": ["ATA", "ATG", '
                      '"GTG"], "codons": {"TTT": "Phe", "TCT": "Ser", "TAT": "Tyr", "TGT": "Cys", "TTC": "Phe", '
                      '"TCC": "Ser", "TAC": "Tyr", "TGC": "Cys", "TTA": "Leu", "TCA": "Ser", "TAA": "Ter", '
                      '"TGA": "Trp", "TTG": "Leu", "TCG": "Ser", "TAG": "Ter", "TGG": "Trp", "CTT": "Thr", '
                      '"CCT": "Pro", "CAT": "His", "CGT": "Arg", "CTC": "Thr", "CCC": "Pro", "CAC": "His", '
                      '"CGC": "Arg", "CTA": "Thr", "CCA": "Pro", "CAA": "Gln", "CGA": "Arg", "CTG": "Thr", '
                      '"CCG": "Pro", "CAG": "Gln", "CGG": "Arg", "ATT": "Ile", "ACT": "Thr", "AAT": "Asn", '
                      '"AGT": "Ser", "ATC": "Ile", "ACC": "Thr", "AAC": "Asn", "AGC": "Ser", "ATA": "Met", '
                      '"ACA": "Thr", "AAA": "Lys", "AGA": "Arg", "ATG": "Met", "ACG": "Thr", "AAG": "Lys", '
                      '"AGG": "Arg", "GTT": "Val", "GCT": "Ala", "GAT": "Asp", "GGT": "Gly", "GTC": "Val", '
                      '"GCC": "Ala", "GAC": "Asp", "GGC": "Gly", "GTA": "Val", "GCA": "Ala", "GAA": "Glu", '
                      '"GGA": "Gly", "GTG": "Val", "GCG": "Ala", "GAG": "Glu", "GGG": "Gly"}}, "4": {"initiators": ['
                      '"GTG", "TTA", "ATC", "ATA", "ATT", "TTG", "CTG", "ATG"], "codons": {"TTT": "Phe", '
                      '"TCT": "Ser", "TAT": "Tyr", "TGT": "Cys", "TTC": "Phe", "TCC": "Ser", "TAC": "Tyr", '
                      '"TGC": "Cys", "TTA": "Leu", "TCA": "Ser", "TAA": "Ter", "TGA": "Trp", "TTG": "Leu", '
                      '"TCG": "Ser", "TAG": "Ter", "TGG": "Trp", "CTT": "Leu", "CCT": "Pro", "CAT": "His", '
                      '"CGT": "Arg", "CTC": "Leu", "CCC": "Pro", "CAC": "His", "CGC": "Arg", "CTA": "Leu", '
                      '"CCA": "Pro", "CAA": "Gln", "CGA": "Arg", "CTG": "Leu", "CCG": "Pro", "CAG": "Gln", '
                      '"CGG": "Arg", "ATT": "Ile", "ACT": "Thr", "AAT": "Asn", "AGT": "Ser", "ATC": "Ile", '
                      '"ACC": "Thr", "AAC": "Asn", "AGC": "Ser", "ATA": "Ile", "ACA": "Thr", "AAA": "Lys", '
                      '"AGA": "Arg", "ATG": "Met", "ACG": "Thr", "AAG": "Lys", "AGG": "Arg", "GTT": "Val", '
                      '"GCT": "Ala", "GAT": "Asp", "GGT": "Gly", "GTC": "Val", "GCC": "Ala", "GAC": "Asp", '
                      '"GGC": "Gly", "GTA": "Val", "GCA": "Ala", "GAA": "Glu", "GGA": "Gly", "GTG": "Val", '
                      '"GCG": "Ala", "GAG": "Glu", "GGG": "Gly"}}, "5": {"initiators": ["GTG", "ATC", "ATA", "ATT", '
                      '"TTG", "ATG"], "codons": {"TTT": "Phe", "TCT": "Ser", "TAT": "Tyr", "TGT": "Cys", '
                      '"TTC": "Phe", "TCC": "Ser", "TAC": "Tyr", "TGC": "Cys", "TTA": "Leu", "TCA": "Ser", '
                      '"TAA": "Ter", "TGA": "Trp", "TTG": "Leu", "TCG": "Ser", "TAG": "Ter", "TGG": "Trp", '
                      '"CTT": "Leu", "CCT": "Pro", "CAT": "His", "CGT": "Arg", "CTC": "Leu", "CCC": "Pro", '
                      '"CAC": "His", "CGC": "Arg", "CTA": "Leu", "CCA": "Pro", "CAA": "Gln", "CGA": "Arg", '
                      '"CTG": "Leu", "CCG": "Pro", "CAG": "Gln", "CGG": "Arg", "ATT": "Ile", "ACT": "Thr", '
                      '"AAT": "Asn", "AGT": "Ser", "ATC": "Ile", "ACC": "Thr", "AAC": "Asn", "AGC": "Ser", '
                      '"ATA": "Met", "ACA": "Thr", "AAA": "Lys", "AGA": "Ser", "ATG": "Met", "ACG": "Thr", '
                      '"AAG": "Lys", "AGG": "Ser", "GTT": "Val", "GCT": "Ala", "GAT": "Asp", "GGT": "Gly", '
                      '"GTC": "Val", "GCC": "Ala", "GAC": "Asp", "GGC": "Gly", "GTA": "Val", "GCA": "Ala", '
                      '"GAA": "Glu", "GGA": "Gly", "GTG": "Val", "GCG": "Ala", "GAG": "Glu", "GGG": "Gly"}}, '
                      '"6": {"initiators": ["ATG"], "codons": {"TTT": "Phe", "TCT": "Ser", "TAT": "Tyr", '
                      '"TGT": "Cys", "TTC": "Phe", "TCC": "Ser", "TAC": "Tyr", "TGC": "Cys", "TTA": "Leu", '
                      '"TCA": "Ser", "TAA": "Gln", "TGA": "Ter", "TTG": "Leu", "TCG": "Ser", "TAG": "Gln", '
                      '"TGG": "Trp", "CTT": "Leu", "CCT": "Pro", "CAT": "His", "CGT": "Arg", "CTC": "Leu", '
                      '"CCC": "Pro", "CAC": "His", "CGC": "Arg", "CTA": "Leu", "CCA": "Pro", "CAA": "Gln", '
                      '"CGA": "Arg", "CTG": "Leu", "CCG": "Pro", "CAG": "Gln", "CGG": "Arg", "ATT": "Ile", '
                      '"ACT": "Thr", "AAT": "Asn", "AGT": "Ser", "ATC": "Ile", "ACC": "Thr", "AAC": "Asn", '
                      '"AGC": "Ser", "ATA": "Ile", "ACA": "Thr", "AAA": "Lys", "AGA": "Arg", "ATG": "Met", '
                      '"ACG": "Thr", "AAG": "Lys", "AGG": "Arg", "GTT": "Val", "GCT": "Ala", "GAT": "Asp", '
                      '"GGT": "Gly", "GTC": "Val", "GCC": "Ala", "GAC": "Asp", "GGC": "Gly", "GTA": "Val", '
                      '"GCA": "Ala", "GAA": "Glu", "GGA": "Gly", "GTG": "Val", "GCG": "Ala", "GAG": "Glu", '
                      '"GGG": "Gly"}}, "9": {"initiators": ["ATG", "GTG"], "codons": {"TTT": "Phe", "TCT": "Ser", '
                      '"TAT": "Tyr", "TGT": "Cys", "TTC": "Phe", "TCC": "Ser", "TAC": "Tyr", "TGC": "Cys", '
                      '"TTA": "Leu", "TCA": "Ser", "TAA": "Ter", "TGA": "Trp", "TTG": "Leu", "TCG": "Ser", '
                      '"TAG": "Ter", "TGG": "Trp", "CTT": "Leu", "CCT": "Pro", "CAT": "His", "CGT": "Arg", '
                      '"CTC": "Leu", "CCC": "Pro", "CAC": "His", "CGC": "Arg", "CTA": "Leu", "CCA": "Pro", '
                      '"CAA": "Gln", "CGA": "Arg", "CTG": "Leu", "CCG": "Pro", "CAG": "Gln", "CGG": "Arg", '
                      '"ATT": "Ile", "ACT": "Thr", "AAT": "Asn", "AGT": "Ser", "ATC": "Ile", "ACC": "Thr", '
                      '"AAC": "Asn", "AGC": "Ser", "ATA": "Ile", "ACA": "Thr", "AAA": "Asn", "AGA": "Ser", '
                      '"ATG": "Met", "ACG": "Thr", "AAG": "Lys", "AGG": "Ser", "GTT": "Val", "GCT": "Ala", '
                      '"GAT": "Asp", "GGT": "Gly", "GTC": "Val", "GCC": "Ala", "GAC": "Asp", "GGC": "Gly", '
                      '"GTA": "Val", "GCA": "Ala", "GAA": "Glu", "GGA": "Gly", "GTG": "Val", "GCG": "Ala", '
                      '"GAG": "Glu", "GGG": "Gly"}}, "10": {"initiators": ["ATG"], "codons": {"TTT": "Phe", '
                      '"TCT": "Ser", "TAT": "Tyr", "TGT": "Cys", "TTC": "Phe", "TCC": "Ser", "TAC": "Tyr", '
                      '"TGC": "Cys", "TTA": "Leu", "TCA": "Ser", "TAA": "Ter", "TGA": "Cys", "TTG": "Leu", '
                      '"TCG": "Ser", "TAG": "Ter", "TGG": "Trp", "CTT": "Leu", "CCT": "Pro", "CAT": "His", '
                      '"CGT": "Arg", "CTC": "Leu", "CCC": "Pro", "CAC": "His", "CGC": "Arg", "CTA": "Leu", '
                      '"CCA": "Pro", "CAA": "Gln", "CGA": "Arg", "CTG": "Leu", "CCG": "Pro", "CAG": "Gln", '
                      '"CGG": "Arg", "ATT": "Ile", "ACT": "Thr", "AAT": "Asn", "AGT": "Ser", "ATC": "Ile", '
                      '"ACC": "Thr", "AAC": "Asn", "AGC": "Ser", "ATA": "Ile", "ACA": "Thr", "AAA": "Lys", '
                      '"AGA": "Arg", "ATG": "Met", "ACG": "Thr", "AAG": "Lys", "AGG": "Arg", "GTT": "Val", '
                      '"GCT": "Ala", "GAT": "Asp", "GGT": "Gly", "GTC": "Val", "GCC": "Ala", "GAC": "Asp", '
                      '"GGC": "Gly", "GTA": "Val", "GCA": "Ala", "GAA": "Glu", "GGA": "Gly", "GTG": "Val", '
                      '"GCG": "Ala", "GAG": "Glu", "GGG": "Gly"}}, "11": {"initiators": ["GTG", "ATC", "ATA", "ATT", '
                      '"TTG", "CTG", "ATG"], "codons": {"TTT": "Phe", "TCT": "Ser", "TAT": "Tyr", "TGT": "Cys", '
                      '"TTC": "Phe", "TCC": "Ser", "TAC": "Tyr", "TGC": "Cys", "TTA": "Leu", "TCA": "Ser", '
                      '"TAA": "Ter", "TGA": "Ter", "TTG": "Leu", "TCG": "Ser", "TAG": "Ter", "TGG": "Trp", '
                      '"CTT": "Leu", "CCT": "Pro", "CAT": "His", "CGT": "Arg", "CTC": "Leu", "CCC": "Pro", '
                      '"CAC": "His", "CGC": "Arg", "CTA": "Leu", "CCA": "Pro", "CAA": "Gln", "CGA": "Arg", '
                      '"CTG": "Leu", "CCG": "Pro", "CAG": "Gln", "CGG": "Arg", "ATT": "Ile", "ACT": "Thr", '
                      '"AAT": "Asn", "AGT": "Ser", "ATC": "Ile", "ACC": "Thr", "AAC": "Asn", "AGC": "Ser", '
                      '"ATA": "Ile", "ACA": "Thr", "AAA": "Lys", "AGA": "Arg", "ATG": "Met", "ACG": "Thr", '
                      '"AAG": "Lys", "AGG": "Arg", "GTT": "Val", "GCT": "Ala", "GAT": "Asp", "GGT": "Gly", '
                      '"GTC": "Val", "GCC": "Ala", "GAC": "Asp", "GGC": "Gly", "GTA": "Val", "GCA": "Ala", '
                      '"GAA": "Glu", "GGA": "Gly", "GTG": "Val", "GCG": "Ala", "GAG": "Glu", "GGG": "Gly"}}, '
                      '"12": {"initiators": ["CTG", "ATG"], "codons": {"TTT": "Phe", "TCT": "Ser", "TAT": "Tyr", '
                      '"TGT": "Cys", "TTC": "Phe", "TCC": "Ser", "TAC": "Tyr", "TGC": "Cys", "TTA": "Leu", '
                      '"TCA": "Ser", "TAA": "Ter", "TGA": "Ter", "TTG": "Leu", "TCG": "Ser", "TAG": "Ter", '
                      '"TGG": "Trp", "CTT": "Leu", "CCT": "Pro", "CAT": "His", "CGT": "Arg", "CTC": "Leu", '
                      '"CCC": "Pro", "CAC": "His", "CGC": "Arg", "CTA": "Leu", "CCA": "Pro", "CAA": "Gln", '
                      '"CGA": "Arg", "CTG": "Ser", "CCG": "Pro", "CAG": "Gln", "CGG": "Arg", "ATT": "Ile", '
                      '"ACT": "Thr", "AAT": "Asn", "AGT": "Ser", "ATC": "Ile", "ACC": "Thr", "AAC": "Asn", '
                      '"AGC": "Ser", "ATA": "Ile", "ACA": "Thr", "AAA": "Lys", "AGA": "Arg", "ATG": "Met", '
                      '"ACG": "Thr", "AAG": "Lys", "AGG": "Arg", "GTT": "Val", "GCT": "Ala", "GAT": "Asp", '
                      '"GGT": "Gly", "GTC": "Val", "GCC": "Ala", "GAC": "Asp", "GGC": "Gly", "GTA": "Val", '
                      '"GCA": "Ala", "GAA": "Glu", "GGA": "Gly", "GTG": "Val", "GCG": "Ala", "GAG": "Glu", '
                      '"GGG": "Gly"}}, "13": {"initiators": ["TTG", "ATA", "ATG", "GTG"], "codons": {"TTT": "Phe", '
                      '"TCT": "Ser", "TAT": "Tyr", "TGT": "Cys", "TTC": "Phe", "TCC": "Ser", "TAC": "Tyr", '
                      '"TGC": "Cys", "TTA": "Leu", "TCA": "Ser", "TAA": "Ter", "TGA": "Trp", "TTG": "Leu", '
                      '"TCG": "Ser", "TAG": "Ter", "TGG": "Trp", "CTT": "Leu", "CCT": "Pro", "CAT": "His", '
                      '"CGT": "Arg", "CTC": "Leu", "CCC": "Pro", "CAC": "His", "CGC": "Arg", "CTA": "Leu", '
                      '"CCA": "Pro", "CAA": "Gln", "CGA": "Arg", "CTG": "Leu", "CCG": "Pro", "CAG": "Gln", '
                      '"CGG": "Arg", "ATT": "Ile", "ACT": "Thr", "AAT": "Asn", "AGT": "Ser", "ATC": "Ile", '
                      '"ACC": "Thr", "AAC": "Asn", "AGC": "Ser", "ATA": "Met", "ACA": "Thr", "AAA": "Lys", '
                      '"AGA": "Gly", "ATG": "Met", "ACG": "Thr", "AAG": "Lys", "AGG": "Gly", "GTT": "Val", '
                      '"GCT": "Ala", "GAT": "Asp", "GGT": "Gly", "GTC": "Val", "GCC": "Ala", "GAC": "Asp", '
                      '"GGC": "Gly", "GTA": "Val", "GCA": "Ala", "GAA": "Glu", "GGA": "Gly", "GTG": "Val", '
                      '"GCG": "Ala", "GAG": "Glu", "GGG": "Gly"}}, "14": {"initiators": ["ATG"], "codons": {"TTT": '
                      '"Phe", "TCT": "Ser", "TAT": "Tyr", "TGT": "Cys", "TTC": "Phe", "TCC": "Ser", "TAC": "Tyr", '
                      '"TGC": "Cys", "TTA": "Leu", "TCA": "Ser", "TAA": "Tyr", "TGA": "Trp", "TTG": "Leu", '
                      '"TCG": "Ser", "TAG": "Ter", "TGG": "Trp", "CTT": "Leu", "CCT": "Pro", "CAT": "His", '
                      '"CGT": "Arg", "CTC": "Leu", "CCC": "Pro", "CAC": "His", "CGC": "Arg", "CTA": "Leu", '
                      '"CCA": "Pro", "CAA": "Gln", "CGA": "Arg", "CTG": "Leu", "CCG": "Pro", "CAG": "Gln", '
                      '"CGG": "Arg", "ATT": "Ile", "ACT": "Thr", "AAT": "Asn", "AGT": "Ser", "ATC": "Ile", '
                      '"ACC": "Thr", "AAC": "Asn", "AGC": "Ser", "ATA": "Ile", "ACA": "Thr", "AAA": "Asn", '
                      '"AGA": "Ser", "ATG": "Met", "ACG": "Thr", "AAG": "Lys", "AGG": "Ser", "GTT": "Val", '
                      '"GCT": "Ala", "GAT": "Asp", "GGT": "Gly", "GTC": "Val", "GCC": "Ala", "GAC": "Asp", '
                      '"GGC": "Gly", "GTA": "Val", "GCA": "Ala", "GAA": "Glu", "GGA": "Gly", "GTG": "Val", '
                      '"GCG": "Ala", "GAG": "Glu", "GGG": "Gly"}}, "15": {"initiators": ["ATG"], "codons": {"TTT": '
                      '"Phe", "TCT": "Ser", "TAT": "Tyr", "TGT": "Cys", "TTC": "Phe", "TCC": "Ser", "TAC": "Tyr", '
                      '"TGC": "Cys", "TTA": "Leu", "TCA": "Ser", "TAA": "Ter", "TGA": "Ter", "TTG": "Leu", '
                      '"TCG": "Ser", "TAG": "Gln", "TGG": "Trp", "CTT": "Leu", "CCT": "Pro", "CAT": "His", '
                      '"CGT": "Arg", "CTC": "Leu", "CCC": "Pro", "CAC": "His", "CGC": "Arg", "CTA": "Leu", '
                      '"CCA": "Pro", "CAA": "Gln", "CGA": "Arg", "CTG": "Leu", "CCG": "Pro", "CAG": "Gln", '
                      '"CGG": "Arg", "ATT": "Ile", "ACT": "Thr", "AAT": "Asn", "AGT": "Ser", "ATC": "Ile", '
                      '"ACC": "Thr", "AAC": "Asn", "AGC": "Ser", "ATA": "Ile", "ACA": "Thr", "AAA": "Lys", '
                      '"AGA": "Arg", "ATG": "Met", "ACG": "Thr", "AAG": "Lys", "AGG": "Arg", "GTT": "Val", '
                      '"GCT": "Ala", "GAT": "Asp", "GGT": "Gly", "GTC": "Val", "GCC": "Ala", "GAC": "Asp", '
                      '"GGC": "Gly", "GTA": "Val", "GCA": "Ala", "GAA": "Glu", "GGA": "Gly", "GTG": "Val", '
                      '"GCG": "Ala", "GAG": "Glu", "GGG": "Gly"}}, "16": {"initiators": ["ATG"], "codons": {"TTT": '
                      '"Phe", "TCT": "Ser", "TAT": "Tyr", "TGT": "Cys", "TTC": "Phe", "TCC": "Ser", "TAC": "Tyr", '
                      '"TGC": "Cys", "TTA": "Leu", "TCA": "Ser", "TAA": "Ter", "TGA": "Ter", "TTG": "Leu", '
                      '"TCG": "Ser", "TAG": "Leu", "TGG": "Trp", "CTT": "Leu", "CCT": "Pro", "CAT": "His", '
                      '"CGT": "Arg", "CTC": "Leu", "CCC": "Pro", "CAC": "His", "CGC": "Arg", "CTA": "Leu", '
                      '"CCA": "Pro", "CAA": "Gln", "CGA": "Arg", "CTG": "Leu", "CCG": "Pro", "CAG": "Gln", '
                      '"CGG": "Arg", "ATT": "Ile", "ACT": "Thr", "AAT": "Asn", "AGT": "Ser", "ATC": "Ile", '
                      '"ACC": "Thr", "AAC": "Asn", "AGC": "Ser", "ATA": "Ile", "ACA": "Thr", "AAA": "Lys", '
                      '"AGA": "Arg", "ATG": "Met", "ACG": "Thr", "AAG": "Lys", "AGG": "Arg", "GTT": "Val", '
                      '"GCT": "Ala", "GAT": "Asp", "GGT": "Gly", "GTC": "Val", "GCC": "Ala", "GAC": "Asp", '
                      '"GGC": "Gly", "GTA": "Val", "GCA": "Ala", "GAA": "Glu", "GGA": "Gly", "GTG": "Val", '
                      '"GCG": "Ala", "GAG": "Glu", "GGG": "Gly"}}, "21": {"initiators": ["ATG", "GTG"], "codons": {'
                      '"TTT": "Phe", "TCT": "Ser", "TAT": "Tyr", "TGT": "Cys", "TTC": "Phe", "TCC": "Ser", '
                      '"TAC": "Tyr", "TGC": "Cys", "TTA": "Leu", "TCA": "Ser", "TAA": "Ter", "TGA": "Trp", '
                      '"TTG": "Leu", "TCG": "Ser", "TAG": "Ter", "TGG": "Trp", "CTT": "Leu", "CCT": "Pro", '
                      '"CAT": "His", "CGT": "Arg", "CTC": "Leu", "CCC": "Pro", "CAC": "His", "CGC": "Arg", '
                      '"CTA": "Leu", "CCA": "Pro", "CAA": "Gln", "CGA": "Arg", "CTG": "Leu", "CCG": "Pro", '
                      '"CAG": "Gln", "CGG": "Arg", "ATT": "Ile", "ACT": "Thr", "AAT": "Asn", "AGT": "Ser", '
                      '"ATC": "Ile", "ACC": "Thr", "AAC": "Asn", "AGC": "Ser", "ATA": "Met", "ACA": "Thr", '
                      '"AAA": "Asn", "AGA": "Ser", "ATG": "Met", "ACG": "Thr", "AAG": "Lys", "AGG": "Ser", '
                      '"GTT": "Val", "GCT": "Ala", "GAT": "Asp", "GGT": "Gly", "GTC": "Val", "GCC": "Ala", '
                      '"GAC": "Asp", "GGC": "Gly", "GTA": "Val", "GCA": "Ala", "GAA": "Glu", "GGA": "Gly", '
                      '"GTG": "Val", "GCG": "Ala", "GAG": "Glu", "GGG": "Gly"}}, "22": {"initiators": ["ATG"], '
                      '"codons": {"TTT": "Phe", "TCT": "Ser", "TAT": "Tyr", "TGT": "Cys", "TTC": "Phe", "TCC": "Ser", '
                      '"TAC": "Tyr", "TGC": "Cys", "TTA": "Leu", "TCA": "Ter", "TAA": "Ter", "TGA": "Ter", '
                      '"TTG": "Leu", "TCG": "Ser", "TAG": "Leu", "TGG": "Trp", "CTT": "Leu", "CCT": "Pro", '
                      '"CAT": "His", "CGT": "Arg", "CTC": "Leu", "CCC": "Pro", "CAC": "His", "CGC": "Arg", '
                      '"CTA": "Leu", "CCA": "Pro", "CAA": "Gln", "CGA": "Arg", "CTG": "Leu", "CCG": "Pro", '
                      '"CAG": "Gln", "CGG": "Arg", "ATT": "Ile", "ACT": "Thr", "AAT": "Asn", "AGT": "Ser", '
                      '"ATC": "Ile", "ACC": "Thr", "AAC": "Asn", "AGC": "Ser", "ATA": "Ile", "ACA": "Thr", '
                      '"AAA": "Lys", "AGA": "Arg", "ATG": "Met", "ACG": "Thr", "AAG": "Lys", "AGG": "Arg", '
                      '"GTT": "Val", "GCT": "Ala", "GAT": "Asp", "GGT": "Gly", "GTC": "Val", "GCC": "Ala", '
                      '"GAC": "Asp", "GGC": "Gly", "GTA": "Val", "GCA": "Ala", "GAA": "Glu", "GGA": "Gly", '
                      '"GTG": "Val", "GCG": "Ala", "GAG": "Glu", "GGG": "Gly"}}, "23": {"initiators": ["ATG", "ATT", '
                      '"GTG"], "codons": {"TTT": "Phe", "TCT": "Ser", "TAT": "Tyr", "TGT": "Cys", "TTC": "Phe", '
                      '"TCC": "Ser", "TAC": "Tyr", "TGC": "Cys", "TTA": "Ter", "TCA": "Ser", "TAA": "Ter", '
                      '"TGA": "Ter", "TTG": "Leu", "TCG": "Ser", "TAG": "Ter", "TGG": "Trp", "CTT": "Leu", '
                      '"CCT": "Pro", "CAT": "His", "CGT": "Arg", "CTC": "Leu", "CCC": "Pro", "CAC": "His", '
                      '"CGC": "Arg", "CTA": "Leu", "CCA": "Pro", "CAA": "Gln", "CGA": "Arg", "CTG": "Leu", '
                      '"CCG": "Pro", "CAG": "Gln", "CGG": "Arg", "ATT": "Ile", "ACT": "Thr", "AAT": "Asn", '
                      '"AGT": "Ser", "ATC": "Ile", "ACC": "Thr", "AAC": "Asn", "AGC": "Ser", "ATA": "Ile", '
                      '"ACA": "Thr", "AAA": "Lys", "AGA": "Arg", "ATG": "Met", "ACG": "Thr", "AAG": "Lys", '
                      '"AGG": "Arg", "GTT": "Val", "GCT": "Ala", "GAT": "Asp", "GGT": "Gly", "GTC": "Val", '
                      '"GCC": "Ala", "GAC": "Asp", "GGC": "Gly", "GTA": "Val", "GCA": "Ala", "GAA": "Glu", '
                      '"GGA": "Gly", "GTG": "Val", "GCG": "Ala", "GAG": "Glu", "GGG": "Gly"}}, "24": {"initiators": ['
                      '"TTG", "CTG", "ATG", "GTG"], "codons": {"TTT": "Phe", "TCT": "Ser", "TAT": "Tyr", '
                      '"TGT": "Cys", "TTC": "Phe", "TCC": "Ser", "TAC": "Tyr", "TGC": "Cys", "TTA": "Leu", '
                      '"TCA": "Ser", "TAA": "Ter", "TGA": "Trp", "TTG": "Leu", "TCG": "Ser", "TAG": "Ter", '
                      '"TGG": "Trp", "CTT": "Leu", "CCT": "Pro", "CAT": "His", "CGT": "Arg", "CTC": "Leu", '
                      '"CCC": "Pro", "CAC": "His", "CGC": "Arg", "CTA": "Leu", "CCA": "Pro", "CAA": "Gln", '
                      '"CGA": "Arg", "CTG": "Leu", "CCG": "Pro", "CAG": "Gln", "CGG": "Arg", "ATT": "Ile", '
                      '"ACT": "Thr", "AAT": "Asn", "AGT": "Ser", "ATC": "Ile", "ACC": "Thr", "AAC": "Asn", '
                      '"AGC": "Ser", "ATA": "Ile", "ACA": "Thr", "AAA": "Lys", "AGA": "Ser", "ATG": "Met", '
                      '"ACG": "Thr", "AAG": "Lys", "AGG": "Lys", "GTT": "Val", "GCT": "Ala", "GAT": "Asp", '
                      '"GGT": "Gly", "GTC": "Val", "GCC": "Ala", "GAC": "Asp", "GGC": "Gly", "GTA": "Val", '
                      '"GCA": "Ala", "GAA": "Glu", "GGA": "Gly", "GTG": "Val", "GCG": "Ala", "GAG": "Glu", '
                      '"GGG": "Gly"}}, "25": {"initiators": ["TTG", "ATG", "GTG"], "codons": {"TTT": "Phe", '
                      '"TCT": "Ser", "TAT": "Tyr", "TGT": "Cys", "TTC": "Phe", "TCC": "Ser", "TAC": "Tyr", '
                      '"TGC": "Cys", "TTA": "Leu", "TCA": "Ser", "TAA": "Ter", "TGA": "Gly", "TTG": "Leu", '
                      '"TCG": "Ser", "TAG": "Ter", "TGG": "Trp", "CTT": "Leu", "CCT": "Pro", "CAT": "His", '
                      '"CGT": "Arg", "CTC": "Leu", "CCC": "Pro", "CAC": "His", "CGC": "Arg", "CTA": "Leu", '
                      '"CCA": "Pro", "CAA": "Gln", "CGA": "Arg", "CTG": "Leu", "CCG": "Pro", "CAG": "Gln", '
                      '"CGG": "Arg", "ATT": "Ile", "ACT": "Thr", "AAT": "Asn", "AGT": "Ser", "ATC": "Ile", '
                      '"ACC": "Thr", "AAC": "Asn", "AGC": "Ser", "ATA": "Ile", "ACA": "Thr", "AAA": "Lys", '
                      '"AGA": "Arg", "ATG": "Met", "ACG": "Thr", "AAG": "Lys", "AGG": "Arg", "GTT": "Val", '
                      '"GCT": "Ala", "GAT": "Asp", "GGT": "Gly", "GTC": "Val", "GCC": "Ala", "GAC": "Asp", '
                      '"GGC": "Gly", "GTA": "Val", "GCA": "Ala", "GAA": "Glu", "GGA": "Gly", "GTG": "Val", '
                      '"GCG": "Ala", "GAG": "Glu", "GGG": "Gly"}}, "26": {"initiators": ["CTG", "ATG"], "codons": {'
                      '"TTT": "Phe", "TCT": "Ser", "TAT": "Tyr", "TGT": "Cys", "TTC": "Phe", "TCC": "Ser", '
                      '"TAC": "Tyr", "TGC": "Cys", "TTA": "Leu", "TCA": "Ser", "TAA": "Ter", "TGA": "Ter", '
                      '"TTG": "Leu", "TCG": "Ser", "TAG": "Ter", "TGG": "Trp", "CTT": "Leu", "CCT": "Pro", '
                      '"CAT": "His", "CGT": "Arg", "CTC": "Leu", "CCC": "Pro", "CAC": "His", "CGC": "Arg", '
                      '"CTA": "Leu", "CCA": "Pro", "CAA": "Gln", "CGA": "Arg", "CTG": "Ala", "CCG": "Pro", '
                      '"CAG": "Gln", "CGG": "Arg", "ATT": "Ile", "ACT": "Thr", "AAT": "Asn", "AGT": "Ser", '
                      '"ATC": "Ile", "ACC": "Thr", "AAC": "Asn", "AGC": "Ser", "ATA": "Ile", "ACA": "Thr", '
                      '"AAA": "Lys", "AGA": "Arg", "ATG": "Met", "ACG": "Thr", "AAG": "Lys", "AGG": "Arg", '
                      '"GTT": "Val", "GCT": "Ala", "GAT": "Asp", "GGT": "Gly", "GTC": "Val", "GCC": "Ala", '
                      '"GAC": "Asp", "GGC": "Gly", "GTA": "Val", "GCA": "Ala", "GAA": "Glu", "GGA": "Gly", '
                      '"GTG": "Val", "GCG": "Ala", "GAG": "Glu", "GGG": "Gly"}}, "27": {"initiators": ["ATG"], '
                      '"codons": {"TTT": "Phe", "TCT": "Ser", "TAT": "Tyr", "TGT": "Cys", "TTC": "Phe", "TCC": "Ser", '
                      '"TAC": "Tyr", "TGC": "Cys", "TTA": "Leu", "TCA": "Ser", "TAA": "Gln", "TGA": "Trp", '
                      '"TTG": "Leu", "TCG": "Ser", "TAG": "Gln", "TGG": "Trp", "CTT": "Leu", "CCT": "Pro", '
                      '"CAT": "His", "CGT": "Arg", "CTC": "Leu", "CCC": "Pro", "CAC": "His", "CGC": "Arg", '
                      '"CTA": "Leu", "CCA": "Pro", "CAA": "Gln", "CGA": "Arg", "CTG": "Leu", "CCG": "Pro", '
                      '"CAG": "Gln", "CGG": "Arg", "ATT": "Ile", "ACT": "Thr", "AAT": "Asn", "AGT": "Ser", '
                      '"ATC": "Ile", "ACC": "Thr", "AAC": "Asn", "AGC": "Ser", "ATA": "Ile", "ACA": "Thr", '
                      '"AAA": "Lys", "AGA": "Arg", "ATG": "Met", "ACG": "Thr", "AAG": "Lys", "AGG": "Arg", '
                      '"GTT": "Val", "GCT": "Ala", "GAT": "Asp", "GGT": "Gly", "GTC": "Val", "GCC": "Ala", '
                      '"GAC": "Asp", "GGC": "Gly", "GTA": "Val", "GCA": "Ala", "GAA": "Glu", "GGA": "Gly", '
                      '"GTG": "Val", "GCG": "Ala", "GAG": "Glu", "GGG": "Gly"}}, "28": {"initiators": ["ATG"], '
                      '"codons": {"TTT": "Phe", "TCT": "Ser", "TAT": "Tyr", "TGT": "Cys", "TTC": "Phe", "TCC": "Ser", '
                      '"TAC": "Tyr", "TGC": "Cys", "TTA": "Leu", "TCA": "Ser", "TAA": "Gln", "TGA": "Trp", '
                      '"TTG": "Leu", "TCG": "Ser", "TAG": "Gln", "TGG": "Trp", "CTT": "Leu", "CCT": "Pro", '
                      '"CAT": "His", "CGT": "Arg", "CTC": "Leu", "CCC": "Pro", "CAC": "His", "CGC": "Arg", '
                      '"CTA": "Leu", "CCA": "Pro", "CAA": "Gln", "CGA": "Arg", "CTG": "Leu", "CCG": "Pro", '
                      '"CAG": "Gln", "CGG": "Arg", "ATT": "Ile", "ACT": "Thr", "AAT": "Asn", "AGT": "Ser", '
                      '"ATC": "Ile", "ACC": "Thr", "AAC": "Asn", "AGC": "Ser", "ATA": "Ile", "ACA": "Thr", '
                      '"AAA": "Lys", "AGA": "Arg", "ATG": "Met", "ACG": "Thr", "AAG": "Lys", "AGG": "Arg", '
                      '"GTT": "Val", "GCT": "Ala", "GAT": "Asp", "GGT": "Gly", "GTC": "Val", "GCC": "Ala", '
                      '"GAC": "Asp", "GGC": "Gly", "GTA": "Val", "GCA": "Ala", "GAA": "Glu", "GGA": "Gly", '
                      '"GTG": "Val", "GCG": "Ala", "GAG": "Glu", "GGG": "Gly"}}, "29": {"initiators": ["ATG"], '
                      '"codons": {"TTT": "Phe", "TCT": "Ser", "TAT": "Tyr", "TGT": "Cys", "TTC": "Phe", "TCC": "Ser", '
                      '"TAC": "Tyr", "TGC": "Cys", "TTA": "Leu", "TCA": "Ser", "TAA": "Tyr", "TGA": "Ter", '
                      '"TTG": "Leu", "TCG": "Ser", "TAG": "Tyr", "TGG": "Trp", "CTT": "Leu", "CCT": "Pro", '
                      '"CAT": "His", "CGT": "Arg", "CTC": "Leu", "CCC": "Pro", "CAC": "His", "CGC": "Arg", '
                      '"CTA": "Leu", "CCA": "Pro", "CAA": "Gln", "CGA": "Arg", "CTG": "Leu", "CCG": "Pro", '
                      '"CAG": "Gln", "CGG": "Arg", "ATT": "Ile", "ACT": "Thr", "AAT": "Asn", "AGT": "Ser", '
                      '"ATC": "Ile", "ACC": "Thr", "AAC": "Asn", "AGC": "Ser", "ATA": "Ile", "ACA": "Thr", '
                      '"AAA": "Lys", "AGA": "Arg", "ATG": "Met", "ACG": "Thr", "AAG": "Lys", "AGG": "Arg", '
                      '"GTT": "Val", "GCT": "Ala", "GAT": "Asp", "GGT": "Gly", "GTC": "Val", "GCC": "Ala", '
                      '"GAC": "Asp", "GGC": "Gly", "GTA": "Val", "GCA": "Ala", "GAA": "Glu", "GGA": "Gly", '
                      '"GTG": "Val", "GCG": "Ala", "GAG": "Glu", "GGG": "Gly"}}, "30": {"initiators": ["ATG"], '
                      '"codons": {"TTT": "Phe", "TCT": "Ser", "TAT": "Tyr", "TGT": "Cys", "TTC": "Phe", "TCC": "Ser", '
                      '"TAC": "Tyr", "TGC": "Cys", "TTA": "Leu", "TCA": "Ser", "TAA": "Glu", "TGA": "Ter", '
                      '"TTG": "Leu", "TCG": "Ser", "TAG": "Glu", "TGG": "Trp", "CTT": "Leu", "CCT": "Pro", '
                      '"CAT": "His", "CGT": "Arg", "CTC": "Leu", "CCC": "Pro", "CAC": "His", "CGC": "Arg", '
                      '"CTA": "Leu", "CCA": "Pro", "CAA": "Gln", "CGA": "Arg", "CTG": "Leu", "CCG": "Pro", '
                      '"CAG": "Gln", "CGG": "Arg", "ATT": "Ile", "ACT": "Thr", "AAT": "Asn", "AGT": "Ser", '
                      '"ATC": "Ile", "ACC": "Thr", "AAC": "Asn", "AGC": "Ser", "ATA": "Ile", "ACA": "Thr", '
                      '"AAA": "Lys", "AGA": "Arg", "ATG": "Met", "ACG": "Thr", "AAG": "Lys", "AGG": "Arg", '
                      '"GTT": "Val", "GCT": "Ala", "GAT": "Asp", "GGT": "Gly", "GTC": "Val", "GCC": "Ala", '
                      '"GAC": "Asp", "GGC": "Gly", "GTA": "Val", "GCA": "Ala", "GAA": "Glu", "GGA": "Gly", '
                      '"GTG": "Val", "GCG": "Ala", "GAG": "Glu", "GGG": "Gly"}}, "31": {"initiators": ["ATG"], '
                      '"codons": {"TTT": "Phe", "TCT": "Ser", "TAT": "Tyr", "TGT": "Cys", "TTC": "Phe", "TCC": "Ser", '
                      '"TAC": "Tyr", "TGC": "Cys", "TTA": "Leu", "TCA": "Ser", "TAA": "Glu", "TGA": "Trp", '
                      '"TTG": "Leu", "TCG": "Ser", "TAG": "Glu", "TGG": "Trp", "CTT": "Leu", "CCT": "Pro", '
                      '"CAT": "His", "CGT": "Arg", "CTC": "Leu", "CCC": "Pro", "CAC": "His", "CGC": "Arg", '
                      '"CTA": "Leu", "CCA": "Pro", "CAA": "Gln", "CGA": "Arg", "CTG": "Leu", "CCG": "Pro", '
                      '"CAG": "Gln", "CGG": "Arg", "ATT": "Ile", "ACT": "Thr", "AAT": "Asn", "AGT": "Ser", '
                      '"ATC": "Ile", "ACC": "Thr", "AAC": "Asn", "AGC": "Ser", "ATA": "Ile", "ACA": "Thr", '
                      '"AAA": "Lys", "AGA": "Arg", "ATG": "Met", "ACG": "Thr", "AAG": "Lys", "AGG": "Arg", '
                      '"GTT": "Val", "GCT": "Ala", "GAT": "Asp", "GGT": "Gly", "GTC": "Val", "GCC": "Ala", '
                      '"GAC": "Asp", "GGC": "Gly", "GTA": "Val", "GCA": "Ala", "GAA": "Glu", "GGA": "Gly", '
                      '"GTG": "Val", "GCG": "Ala", "GAG": "Glu", "GGG": "Gly"}}}')

def all_possible_codons():
    """
    ALl 64 codons in order. This is just a simplified function to ensure we get them all
    :return: a set of all 64 codons.
    """
    return {
        'AAA', 'AAC', 'AAG', 'AAT', 'ACA', 'ACC', 'ACG', 'ACT', 'AGA', 'AGC', 'AGG', 'AGT', 'ATA', 'ATC', 'ATG', 'ATT',
        'CAA', 'CAC', 'CAG', 'CAT', 'CCA', 'CCC', 'CCG', 'CCT', 'CGA', 'CGC', 'CGG', 'CGT', 'CTA', 'CTC', 'CTG', 'CTT',
        'GAA', 'GAC', 'GAG', 'GAT', 'GCA', 'GCC', 'GCG', 'GCT', 'GGA', 'GGC', 'GGG', 'GGT', 'GTA', 'GTC', 'GTG', 'GTT',
        'TAA', 'TAC', 'TAG', 'TAT', 'TCA', 'TCC', 'TCG', 'TCT', 'TGA', 'TGC', 'TGG', 'TGT', 'TTA', 'TTC', 'TTG', 'TTT'
    }

def three_letters_to_one_letter():
    """
    By default we use three letter amino acid encoding, just because. This provides a translation back to one letter
    :return: a dict of amino acid codes
    """
    return {
        "Ala" : "A", "Arg" : "R", "Asn" : "N", "Asp" : "D", "Cys" : "C", "Gln" : "Q", "Glu" : "E", "Gly" : "G",
        "His" : "H", "Ile" : "I", "Leu" : "L", "Lys" : "K", "Met" : "M", "Phe" : "F", "Pro" : "P", "Ser" : "S",
        "Thr" : "T", "Trp" : "W", "Tyr" : "Y", "Val" : "V", "Ter" : "*"
    }